package com.project.society.model;

import lombok.*;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDate;
import java.time.LocalDateTime;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "maintenance")
public class Maintenance {

    @Id
    private String id;

    private String societyId;

    private String userId;

    private String residentName;

    private String flatNumber;

    private Double amount;

    // NEW
    private Integer month;

    // NEW
    private Integer year;

    private LocalDate dueDate;

    private String paymentStatus = "PENDING";

    private String razorpayOrderId;

    private String razorpayPaymentId;

    private String razorpaySignature;

    private LocalDateTime paidAt;

    // NEW
    private Boolean autoGenerated = true;

    private LocalDateTime createdAt;

    private LocalDateTime updatedAt;
}