package com.project.society.scheduler;

import com.project.society.model.Maintenance;
import com.project.society.repository.MaintenanceRepository;

import lombok.RequiredArgsConstructor;

import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

@Component
@RequiredArgsConstructor
public class MaintenanceScheduler {

    private final MaintenanceRepository repo;

    @Scheduled(cron = "0 0 1 25 * ?")
    public void generateMonthlyMaintenance(){

        List<Maintenance> oldRecords =
                repo.findAll();

        int nextMonth =
                LocalDate.now()
                        .plusMonths(1)
                        .getMonthValue();

        int year =
                LocalDate.now()
                        .plusMonths(1)
                        .getYear();

        for(Maintenance old : oldRecords){

            boolean exists =

                    repo.existsByUserIdAndMonthAndYear(

                            old.getUserId(),

                            nextMonth,

                            year
                    );

            if(!exists){

                Maintenance m =
                        new Maintenance();

                m.setSocietyId(
                        old.getSocietyId()
                );

                m.setUserId(
                        old.getUserId()
                );

                m.setResidentName(
                        old.getResidentName()
                );

                m.setFlatNumber(
                        old.getFlatNumber()
                );

                m.setAmount(
                        old.getAmount()
                );

                m.setMonth(
                        nextMonth
                );

                m.setYear(
                        year
                );

                m.setDueDate(

                        LocalDate.of(
                                year,
                                nextMonth,
                                5
                        )
                );

                m.setPaymentStatus(
                        "PENDING"
                );

                m.setAutoGenerated(
                        true
                );

                m.setCreatedAt(
                        LocalDateTime.now()
                );

                m.setUpdatedAt(
                        LocalDateTime.now()
                );

                repo.save(m);
            }
        }
    }
}